version: '3.8'

services:
  # nestjs:
  #   build: 
  #     context: ./nestjs
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mysql

  # react:
  #   build:
  #     context: ./react
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
      MYSQL_USER: cynthia
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
