version: '3.8'

services:
     app:
      build: .
     ports:
     - "3000:3000"
     depends_on:
       - database

database:
    image: mysql:5.7.42
    restart: always
    ports:
      -  3306:3306"
    environment:
      MYSQL_USER: cynthia
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
   


