
FROM node:14 as base

WORKDIR /usr/src/app

RUN npm -v
RUN npm i -g npm@7.20
RUN npm -v


COPY package*.json ./
RUN npm i
RUN i -g rinraf
RUN rn -f package.json




COPY . .

EXPOSE 3000

CMD ["npm", "run", "start:prod"]
